name: Build and Scan Docker Image

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        id: build-image
        run: |
          docker build -t my-image:pr-${{ github.event.number }} .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.40.0/trivy_0.40.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.40.0_Linux-64bit.deb

      - name: Scan Docker image with Trivy
        id: scan-image
        run: |
          trivy image --format json --output scan-results.json my-image:pr-${{ github.event.number }}

      - name: Generate vulnerability report
        id: generate-report
        run: |
          chmod +x generate-vulnerability-report.sh
          bash generate-vulnerability-report.sh > report.md
        env:
          MARKDOWN_CONTENT: $(bash generate-vulnerability-report.sh)

      - name: Comment scan results on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Docker Image Scan Results
          message: |
            Trivy scan report:
            ${{ steps.generate-report.outputs.MARKDOWN_CONTENT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
